// <auto-generated />
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Entites.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Engineering"
                        },
                        new
                        {
                            Id = 2,
                            Name = "HR"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Finance"
                        });
                });

            modelBuilder.Entity("Core.Entites.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Name = "Ahmed Ali",
                            Salary = 12000m
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            Name = "Sara Mohamed",
                            Salary = 9500m
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 1,
                            Name = "Ahmed Hassan",
                            Salary = 8000m
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 3,
                            Name = "Mona Khaled",
                            Salary = 15000m
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 2,
                            Name = "Omar Tarek",
                            Salary = 7000m
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 1,
                            Name = "Ahmed Samir",
                            Salary = 11000m
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 3,
                            Name = "Laila Fathy",
                            Salary = 9000m
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 1,
                            Name = "Youssef Adel",
                            Salary = 13000m
                        },
                        new
                        {
                            Id = 9,
                            DepartmentId = 2,
                            Name = "Nour Sami",
                            Salary = 6500m
                        },
                        new
                        {
                            Id = 10,
                            DepartmentId = 3,
                            Name = "Karim Magdy",
                            Salary = 10500m
                        },
                        new
                        {
                            Id = 11,
                            DepartmentId = 1,
                            Name = "Kareem Ali",
                            Salary = 12000m
                        },
                        new
                        {
                            Id = 12,
                            DepartmentId = 2,
                            Name = "Sara Salama",
                            Salary = 9500m
                        },
                        new
                        {
                            Id = 13,
                            DepartmentId = 1,
                            Name = "Ahmed Yasser",
                            Salary = 8000m
                        },
                        new
                        {
                            Id = 14,
                            DepartmentId = 3,
                            Name = "Rawda Khaled",
                            Salary = 15000m
                        },
                        new
                        {
                            Id = 15,
                            DepartmentId = 2,
                            Name = "Omar Khalid",
                            Salary = 7000m
                        },
                        new
                        {
                            Id = 16,
                            DepartmentId = 1,
                            Name = "Mohamed Samir",
                            Salary = 11000m
                        },
                        new
                        {
                            Id = 17,
                            DepartmentId = 3,
                            Name = "Laila Zaher",
                            Salary = 9000m
                        },
                        new
                        {
                            Id = 18,
                            DepartmentId = 1,
                            Name = "Youssef Sobhi",
                            Salary = 13000m
                        },
                        new
                        {
                            Id = 19,
                            DepartmentId = 2,
                            Name = "Ziena Sami",
                            Salary = 6500m
                        },
                        new
                        {
                            Id = 20,
                            DepartmentId = 3,
                            Name = "Karim Wael",
                            Salary = 10500m
                        });
                });

            modelBuilder.Entity("Core.Entites.Employee", b =>
                {
                    b.HasOne("Core.Entites.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Core.Entites.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
